borders.go
color.go

This PR changes internal behavior so that the color profile and terminal background color aren't checked until the values are needed. Once the lookups have been done once they won't be performed again.
Checking the terminal’s background color can potentially be an expensive call, so if the user isn’t using `lipgloss.AdaptiveColor` there’s really no reason to perform the check.
There's also a small API change: `lipgloss.ColorProfile`, a variable containing the color profile value, is now `lipgloss.ColorProfile()`, a function returning the color profile value.

Don't check color profile and terminal darkness until absolutely necessary

---

ansi_unix.go
ansi_windows.go
color.go
style.go

This PR includes support for the Windows 10 legacy command console, which includes cmd.exe and the standalone PowerShell application on Windows. Lip Gloss should now "just work" on those consoles.
Note that this update isn't needed in [Windows Terminal](https://github.com/microsoft/terminal).

Support for legacy Windows consoles

---

borders.go
example/main.go
set.go
style.go
unset.go

This PR drops the _Color_ suffixes from the foreground and background portions of the border API so that the border API better matches the rest of the API. For example, `BorderTopForegroundColor` is now simply `BorderTopForeground`.
Additionally, `UnsetBorderColor` has been removed. To unset border colors use `UnsetBorderForeground` and `UnsetBorderBackground`.

Border Color API Consistency

---

set.go

And the moment, Lip Gloss only supports positive values in sizing operations. This PR sets values to `0` in the following methods for all arguments below `0`:
* `Width`
* `Height`
* `MaxWidth`
* `MaxHeight`
* `Padding`
* `PaddingTop`
* `PaddingRight`
* `PaddingBottom`
* `PaddingLeft`
* `MarginTop`
* `MarginRight`
* `MarginBottom`
* `MarginLeft`
A note on types: internally we use `int`s as it's Go's default type of integer and makes working with functions like `len` a bit easier. This could be an argument for using `uint` internally.

Keep margins, padding, widths, and heights positive

---

style.go

If no rules are set, skip rendering. This also skips enabling ANSI in the Windows legacy console, ensuring that it's not run until absolutely necessary.

Short circuit rendering if no style rules are set

---

color.go
unset.go

This PR queries the terminal background color on package initialization, avoiding potential race conditions (and lag) that could occur previously when it was queried only when first needed, which had a very high likelihood of happening during a render.
See charmbracelet/bubbletea#86, where this issue was discovered.

Query terminal background color on init

---

get.go

This PR adds getters for all style rules, enabling you to query your styles, which can be handy when building your layouts, particularly when style settings are variable. For example:
```go
if someStyle.GetMarginLeft() > lipgloss.Width(spinner) + lipgloss.Width(gap) {
// jam the spinner in the left gutter
} else {
// just put the spinner on the right
}
```

Add getters for all style rules

---

example/main.go

A correction in the example, as noted in the Fediverse: https://cathode.church/@meena/106002336386354738

Quince is not a citrus fruit

---

README.md
borders.go
example/go.sum
go.mod
go.sum
size.go

This PR adds support for fancier borders, fixes some bugs, adds a helper function for measuring text block sizes, and improves the README.
With the new border support, it's possible to construct borders from multiple runes, such as this:
* Support for multi-rune borders
* Added `Size() (int, int)` for returning the width and the height of a block in one go
* Bump go-runewidth to fix some emoji mis-measuring
* Fix a panic that could happen in custom borders

Borders, sizing, and an emoji-fix

---

README.md
color.go
color_test.go
runes_test.go

This PR allows the color profile to be set on a package-wide basis via `lipgloss.SetColorProfile`. This is mostly intended for testing purposes. By default, Lip Gloss will use the best available color profile, which is want you will want to use in your terminal applications.
Available color profiles are:
* `termenv.Ascii`: black and white (1-bit)
* `termenv.ANSI`: 16 colors (4-bit)
* `termenv.ANSI256`: 256 colors, (8-bit)
* `termenv.TrueColor`: 16,777,216 colors (24-bit)
The `SetColorProfile` method is thread-safe.
Closes #33.

Add SetColorProfile for explicitly setting the color profile

---

README.md

We renamed these functions, updated the examples, but apparently forgot the README. Oops.

Fix README examples for joins

---

README.md

The Stringer example in the README was incorrect. But not anymore.

Correct stringer interface example in README

---

borders.go
get.go

This PR adds convenience functions for querying styles’ horizontal and vertical gaps, as well as new methods for querying border sizing. The most useful of these are, perhaps, the methods for querying vertical and horizontal margins, padding and border widths all at once:
* `Style.GetFrameSize() (x, y int)`
* `Style.GetVerticalFrameSize() int`
* `Style.GetHorizontalFrameSize() int`
* Border-level methods for returning the width of an edge. The width widest rune in an edge will be returned.
* `Border.GetTopSize() int`
* `Border.GetRightSize() int`
* `Border.GetBottomSize() int`
* `Border.GetLeftSize() int` 
* Style-level methods for returning the width of a border edge. The width widest rune in an edge will be returned.
* `Style.GetBorderTopSize() int`
* `Style.GetBorderRightSize() int`
* …

Whitespace and Border Measurement

---

style.go

This update forces strings that run wider than the given width to wrap as a sensible default.
So, given the following code:
```go
s := lipgloss.NewStyle().
BorderStyle(lipgloss.RoundedBorder()).
Width(5).
Render("Schnurrbart")
fmt.Println(s)
```
Prior to this update it would render as such:
```
╭─────╮
│Schnurrbart│
╰─────╯
```
After this update is renders as follows:
```
╭─────╮
│Schnu│
│rrbar│
│t    │
╰─────╯
```
We could potentially introduce a setting to disallow this behavior, however we'll examine that use when the need arises. Special thanks to @erikgeiser for the [upstream PR](https://github.com/muesli/reflow/pull/30) that made this a cinch.
Closes #43.

Force-wrap long Strings

---

.github/workflows/lint-soft.yml
.golangci-soft.yml
.golangci.yml
ansi_unix.go

Soft-enforced linters will only annotate code changes, hard-enforced linters actually make the workflow fail if they encounter an issue.
You can run the soft linters manually on your machine:
```bash
golangci-lint run --config .golangci-soft.yml
```

Add separate sets of hard- and soft-enforced linters

---

go.mod
go.sum

This fixes an issue with (Circle-)CIs not responding to OSC queries.
See discussion on https://github.com/minio/mc/issues/3938.

Bump termenv to v0.10.0

---

color.go

This change prevents Lipgloss from querying the terminal's background color setting on init. Instead, the background color will get queried the first time the setting gets accessed by HasDarkBackground, and the result will be cached.
Furthermore SetHasDarkBackground(bool) has been added, which explicitly sets a value and avoids the automatic detection from ever being run.

Lazily detect background color setting

---

color.go

With `CLICOLOR_FORCE` set, this enables ANSI output even when writing to a non-terminal.

Use termenv's EnvColorProfile, which respects NO_COLOR and CLICOLOR_FORCE env vars

---

ansi_windows.go

Keeps it in a central place at the bottom of the stack. Should eventually migrate the other apps using this little code snippet as well.

Use termenv to enable Windows virtual terminal processing

---

join.go
join_test.go

Currently, JoinVertical displays like this:
```
JoinVertical(0.00, "A", "BBBB")
A   
BBBB
JoinVertical(0.25, "A", "BBBB")
A 
BBBB
JoinVertical(0.75, "A", "BBBB")
A  
BBBB
JoinVertical(1.00, "A", "BBBB")
A
BBBB
```
It seems more natural that 0.25 would be 25% of the way from 0 to 1, and 0.75 would be 75% of the way from 0 to 1. This pull request switches to that behavior, and adds a regression test for the change.

Fix JoinVertical behavior for non-edge non-center alignments

---

example/vet/main.go
style.go

It's contra intuitive that `backgroundKey` is the only key that is **always inherited**.

don't overwrite background when inheriting

---

style.go

The old comment implied that the argument would overwrite, but this is different from the actual behavior which is to NOT overwrite.  This updates the comment to reflect this behavior.

Clarify Inherit comment

---

style.go

`strings.Replace(str, "\n", "", -1)` is not as explicit as `strings.ReplaceAll(str, "\n", "")` , and thus, the latter should be preferred.

Use ReplaceAll instead of Replace with n=-1

---

color.go
color_test.go
go.mod

This PR allows us to drop the extra `go-colorful` dependency while maintaining compatibility with `color.Color`.

chore: drop go-colorful dependency (but it's a great lib)

---

color.go
join.go
set.go

Example code in GoDocs want to be intended with tabs these days. This revision was made automatically via `golangci-lint run --fix`.

docs(lint): update example code in GoDocs per new style standard

---

color.go
join.go
set.go

This revision introduces two new color types `CompleteColor` and `CompleteAdaptiveColor`. Not for the faint of heart, these types are for bypassing automatic color interpolation so you can specify exact colors for all color profiles:
```go
cc := CompleteColor{
TrueColor: "#6B51FF",
ANSI256: "63",
ANSI: "5",
}
cac := CompleteAdaptiveColor{
Light: CompleteColor{
TrueColor: "#FF51CE",
ANSI256: "213",
ANSI: "5",
},
Dark: CompleteColor{
TrueColor: "#6B51FF",
ANSI256: "63",
ANSI: "5",
},
}
```
Keep in mind that profiles that do not receive definitions will not be interpolated and will render as black.

feat: Non-Interpolated Colors

---

color.go
color_test.go

Fixed RGBA rejecting non-hex color values as invalid. Added the full color test-suite while I was at it.

fix: RGBA implementations for non-hex color values

---

get.go
runes.go
set.go
style.go

While reviewing the code I came across some typos and stale variable references.

docs: minor fixes to comments

---

borders.go
set.go

By having the same color for the border and the background of the element, it gives some cool results:
For context, in a game where you can buy upgrades, you can show the user the ones that have been already bought, the ones they can buy, and the ones still locked:
I think it could be a useful addition, for example when you want to highlight something as if it was a button.
---
Quick testing:
```go
package main
import (
"fmt"
"github.com/charmbracelet/lipgloss"
)
var (
innerBorder = lipgloss.Border{
Top:         "▄",
Bottom:      "▀",
Left:        "▐",
Right:       "▌",
TopLeft:     "▗",
TopRight:    "▖",
BottomLeft:  "▝",
BottomRight: "▘",
}
)
func main() {
fmt.Println()
color := lipgloss.Color("#00f5d4)")
testBorders := lipgloss.NewStyle().Foreground(lipgloss.Color("#333")).Background(co …
```

Add BlockBorder, OuterHalfBlockBorder, and InnerHalfBlockBorder border styles

---

style_test.go

Multiple lipgloss renderer instances can end up using the same default termenv.Output. This leads to a race condition when manipulating the ColorProfile concurrently.
We could mutex protect the standard output in termenv, but it feels like a weak promise, as the rest of the Output wouldn't (and probably shouldn't) get protected. Protecting it in lipgloss itself would require a global lock however.
I can't come up with a proper use-case for this scenario, and therefore we shift this responsibility to the user.

fix: don't concurrently change output profiles

---

get.go

Current functions to access the width of the borders directly on `lipgloss.Style`.
- `GetBorderTopWidth`
- `GetBorderLeftSize`
- `GetBorderBottomSize`
- `GetBorderRightSize`
From this list `GetBorderTopWidth` is a bit of an odd function name compared to the rest because it has different suffix. This PR adds `GetBorderTopSize` and deprecates `GetBorderTopWidth`.

chore: unify get border size function names

---

README.md
examples/layout/main.go
examples/ssh/main.go
renderer.go

Minor documentation updates in anticipation of the next release.

Documentation

---

renderer.go
style.go

Creating a _new_ global termenv output clashes with the default global termenv output leading the terminal to block and freeze. Share the default termenv output with the global default lipgloss renderer.
Needs: https://github.com/muesli/termenv/pull/121

fix(renderer): use termenv default renderer

---

go.mod
go.sum

chore: bump termenv to v0.15.1

---

get.go
set.go
style.go
style_test.go
unset.go

Lip Gloss currently mis-measures a tab (i.e. a `\t`) at 0 cells wide when they actually render at different widths in different terminals (usually 8 cells, sometimes 4 cells). For theses reasons tabs are almost never what you want when designing layouts for TUIs.
With this revision, a tab will get converted to 4 spaces by default—so this is a behavioral change—but you can customize the behavior and disable it entirely with the new `TabWidth(int)` method.
```go
s := lipgloss.NewStyle()        // 4 spaces per tab, the default
s = s.TabWidth(2)               // 2 spaces per tab
s = s.TabWidth(0)               // remove tabs
s = s.TabWidth(-1)              // don't convert tabs to spaces
s = s.TabWidth(NoTabConversion) // alias of the above
```
Disable the feature with `Style.TabWidth(-1)` …

feat: convert tabs to spaces with `Style.TabWidth(int)`

---

align.go
color.go
join.go
position.go
set.go
style.go

Generally run-of-the-mill directives to disable magic number and exhaustive switches. Reasonings should be self explanatory while reading the code and comments, where applicable.

chore(lint): add various nolint directives

---

README.md
table/table.go

Minor copyedits to the table section of the README and GoDocs. Also moved the table section after the whitespace section to keep the top level package stuff together, as well as keep the table image from breaking things up to much.

docs(table): README and GoDoc edits

---

get.go

In both `GetHorizontalBorderSize` and `GetVerticalBorderSize`, computing size directly using `getBorderStyle()` can not take into accounts that some borders ("top", maybe "right", "bottom", whatever...) could have been disabled, leading to incorrect results.
This is well done in each individual `GetBorder[Top|Right|Bottom|Left]Size`like this: https://github.com/charmbracelet/lipgloss/blob/df8b3fa1f20885458615189fa0558c6226be8240/get.go#L303-L305
So this pull request just make use of this correct behavior :)

Fix both GetHorizontalBorderSize and GetVerticalBorderSize

---

get.go
set.go
style.go
style_test.go
unset.go

So with this you can basically:
```go
s := NewStyle().Transform(strings.ToUpper)
fmt.Println(s.Render("raow!") // "RAOW!"
```
Some things to consider:
* Should it accept multiple functions?
* Is `Transform` the best name for this?
* Should it ignore ANSI sequences?
Closes #229.

feat: Style.Transform for altering strings at render time

---

style.go
style_test.go

An empty string could not have padding applied on the right side.
Issue: #252

Fix adding right padding to empty string

---

style.go

The `padLeft` and `padRight` functions were nearly identical and could benefit from being refactored to share common code.
A new function called `pad` was added that applies padding based on the sign of the amount of padding needed. A positive value applies padding to the right side while a negative value applies padding to the left side.
Issue: #252

Refactor padding functions

---

go.mod
go.sum
table/table.go
table/table_test.go

Table cells (including the header) may contain ANSI codes. When determining the width of these cells, ANSI was not excluded.
The `reflow` package has the same truncate function that is aware of ANSI. This improves cell width calculation and correctly truncates.

Fix truncate of table cells containing ANSI

---

.github/workflows/build.yml
borders.go
go.mod
go.sum

The function `maxRuneWidth` was using a flawed approach by only evaluating strings based on each rune. The `uniseg` package provides a more accurate method based on grapheme clusters.
This change switches over to the improved implementation which should achieve better results when determining the maximum width of all grapheme clusters in a string.

Improve maximum width of characters in a string

---

borders.go

When a style has a border set and an empty string is rendered, it should still render the border. When the left border is set, width is incremented by 1, so in most cases the width will not be 0.
When we render an empty string, with a double border and no left border we expect the following:
```
╗
║
╝
```
But if we don't render a horizontal edge when the string width is less than 1 we see this:
```
║
```
The string width can't be lower than 0, so we can safely remove the (width < 1) check to create the expected behavior.

fix: always render horizontal border edge when enabled

---

style.go

Fix possible nil panic

---

style.go
style_test.go

This patch fixes a bug where string transforms were applied after styling, potentially altering ANSI sequences.

fix: transform shouldn't operate on ANSI sequences

---

go.mod
go.sum

Upgrade dependencies to latest stable versions.
As part of this dependency upgrade, the `term` package is being updated to include an important fix for wrapping strings containing ANSI codes. See charmbracelet/x/issues/58 for more details.

chore(deps): Upgrade dependencies

---

README.md
style.go

Small update here mostly to tell people how to resolve deprecation warnings in-editor.

chore(docs): doc updates with regard to style.Copy() deprecation

---

style.go

When I create binaries for each OS using goreleaser, the propKeys
generates an int overflow since the iota duplicates for each propKey
This commit changes the int type to works well with binaries generated for arm and i386 archs.

fix: Change the propkeys from int to int64

---

list/enumerations.go
list/list.go
tree/enumerator.go
tree/tree.go

WIP: improving godoc given my experience checkin' out the API
--- 
Viewing changes:
`godoc -http=localhost:6060` then connect to `localhost:6060` in browser. From there, look at the list and tree godoc

docs: improve godoc for trees and lists

---

set.go

You can get the exact same effect with margins and padding.

feat: deprecate Style.ColorWhitespace

---

unset.go

This looks like a looong standing typo :)
This is the only one method ending by "Color". To avoid breaking changes, i've just copy/paste to a new one, directly call this new one, and add a deprecation notice.

fix: Deprecate UnsetBorderTopBackgroundColor in favor of UnsetBorderTopBackground

---

README.md
examples/tree/makeup/main.go
examples/tree/simple/main.go
examples/tree/toggle/main.go

Mostly just attention to detail stuff.

chore(readme): minor tree-related readme edits

---

table/table.go
table/table_test.go
tree/tree_test.go

Fixes https://github.com/charmbracelet/lipgloss/issues/356
* `table/table.go`: Modified the `constructRow` method to accept an `isOverflow` parameter, allowing rows to be rendered as overflow rows with ellipsis when necessary.
* `table/table.go`: Updated the `String` method to calculate the available height for rendering rows and handle the rendering of overflow rows correctly. Most of this lives in the new `constructRows` method.
* `table/table_test.go`: Added unit tests for the `Height` method.
* `table/table.go`: Added a boolean `useManualHeight` to the `Table` struct. I thought it would be good to maintain the existing functionality (auto table height) by default. I've put this in one commit so it can be easily removed if needed. The `useManualHeight` boolean tracks whether the user …

fix(table): use table height

---

README.md

Make the "Rendering Tables" header consistent with "Rendering Lists" and "Rendering Trees".

docs(readme): fix heading level

---

style.go
style_test.go
table/table_test.go

If a string contains carriage returns `\r`, it will cause some funky issues when rendering. More specifically any time we do any string concatenation, string A will be overwritten by string B instead of appended.
this is an example log output when a string has a `\r` and goes through `alignHorizontal` to pad spaces 
```
2024/10/07 13:36:43 end of horizontal align
git: 'defer' is not a git command. See 'git --help'.
----------------------------------------------------
-----------------------ds are
------------------------------------------
------------------------------------------
----------------------------------------------------
```
After this change:
```
2024/10/07 13:53:24 end of horizontal align
git: 'defer' is not a git command. See 'git --help'. …
```

fix(render): strip carriage returns from strings

---

examples/debug.txt
examples/tree/files/main.go

This updates the `tree/files` example to draw a nested file tree.
For example, here is its walking through the current `examples` directory in this repo:
```
/home/christian/lipgloss/examples
├── go.mod 
├── go.sum 
├── layout 
│   └── main.go 
├── list 
│   ├── duckduckgoose 
│   │   └── main.go 
│   ├── glow 
│   │   └── main.go 
│   ├── grocery 
│   │   └── main.go 
│   ├── roman 
│   │   └── main.go 
│   ├── simple 
│   │   └── main.go 
│   └── sublist 
│       └── main.go 
├── ssh 
│   └── main.go 
├── table 
│   ├── ansi 
│   │   └── main.go 
│   ├── chess 
│   │   └── main.go 
│   ├── demo.tape 
│   ├── languages 
│   │   └── main.go 
│   ├── mindy 
│   │   └── main.go 
│   └── pokemon 
│       └── main.go 
└── tree 
├── background 
│   └── main.go 
├── files 
│   └── main.go 
├── …
```

fix(examples): draw nested structure in file tree example

---

adaptive/adaptive.go
color.go

The revision also expands the comment to demonstrate usage in Bubble Tea.

chore: rename LightDark to Adapt per @bashbunni's acute suggestion

---

README.md
table/table.go

https://github.com/charmbracelet/lipgloss/tree/update-contributing?tab=readme-ov-file#contributing

docs: update contributing guidelines

---

align.go
color.go
set.go
table/util.go
terminal.go

This revision updates magic-number-related lint directives and solves for all other outstanding soft lint issues.

chore(lint): update soft lint directives; fix soft lint issues

---

examples/table/pokemon/main.go

Likely an insignificant change, but I fixed the incorrect romaji for the Bulbasaur line.
Bulbasaur => [Fushigidane](https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)#:~:text=Bulbasaur%20(Japanese%3A%20%E3%83%95%E3%82%B7%E3%82%AE%E3%83%80%E3%83%8D-,fushigidane,-)%20is%20a%20dual)
Ivysaur => [Fushigisou](https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)#:~:text=Bulbasaur%20(Japanese%3A%20%E3%83%95%E3%82%B7%E3%82%AE%E3%83%80%E3%83%8D-,fushigidane,-)%20is%20a%20dual)
Venusaur => [Fushigibana](https://bulbapedia.bulbagarden.net/wiki/Venusaur_(Pok%C3%A9mon)#:~:text=Venusaur%20(Japanese%3A%20%E3%83%95%E3%82%B7%E3%82%AE%E3%83%90%E3%83%8A-,fushigibana,-)%20is%20a%20dual)
The Japanese text is written in [Katakana](https://en.wikipedia.org/wiki/Katakana), one of the …

docs(examples): fix incorrect romanization of bulbasaur line

---

color.go

This commit adds a new function `Complete` that replaces the old `CompleteColor` type. It returns a `CompleteFunc` which takes three colors and returns the appropriate one based on the given color profile.

(v2) feat: complete color support

---

README.md
table/table.go

I'm not sure if we need to include this in the README or not, but added it just in case. Let me know :)
Closes #371

docs: include warning about table offset

---

compat/color.go
query.go

This defaults to true if an error is encountered or if the background color is nil. This is a simplification that makes the function easier to use in practice.
Users can still check for errors by calling BackgroundColor directly.

(v2) refactor: remove error return from HasDarkBackground

---

color.go
compat/color.go

The new behavior of `lipgloss.Color` taking `any` type is ambiguous and can lead to unexpected results. This commit restores the original behavior of `lipgloss.Color` taking a hex string or an int string, and returning a color.Color.
To use a 4-bit color, use `lipgloss.Red`, `lipgloss.Blue`, etc. To use a 16-bit color, use `lipgloss.ANSIColor`. To use a 24-bit color, use `lipgloss.Color`, `lipgloss.RGBColor`, or any other `color.Color` value.
Fixes: https://github.com/charmbracelet/lipgloss/pull/437

(v2) fix: restore lipgloss.Color behavior

---

borders.go
borders_test.go
get.go

When a border style is set and no borders have been explicitly enabled or disabled, a border is implicitly applied to all sides of the block. Prior to this fix border size getters would incorrectly return 0 when an implicit border is set. This revision corrects that behavior.
In other words:
```go
s := lipgloss.NewStyle.Border(lipgloss.NormalBorder)
// Before
fmt.Println(s.GetBorderLeftSize()) // 0
// After
fmt.Println(s.GetBorderLeftSize()) // 1
```

fix: border size getters when implicit borders are present

---

go.mod
go.sum
ranges.go
ranges_test.go

Extracted from https://github.com/charmbracelet/gum/pull/789 , this allows to style ranges of a given string without breaking its current styles.
The resulting ansi sequences aren't that beautiful (as there might be many styles+reset with nothing in them), but it works. We can optimize this later I think.
Also: maybe better waiting for lipgloss v2 and do it there instead. This does not handle renderers for example.

feat: style ranges

---

tree/example_test.go
tree/renderer.go
tree/tree.go
tree/tree_test.go

See examples for usage on these changes. Those examples are testable, so see their output in comment to see how these API changes work.

feat(tree): hide children

---

canvas.go
examples/clickable/main.go
examples/layout/main.go

This series of revisions:
* Removes the ID argument from `NewLayer`
* Changes `Canvas` and `Layer` hit tests to return `Layer`s
* Adds compositing to the `layout` example.

(v2) compositing API edit: no ID argument

---

README.md

1. The header index is actually `-1` and not `0`. Checking for the `table.HeaderRow` const which is set to `-1`.
1. Adding the style definitions so the example is actually complete and can be copy & pasted and ran more easily.

docs: fix table example on readme

---

table/table.go

I found this bug while working on https://github.com/charmbracelet/glamour/issues/402.
We need to account for margins as well as paddings.
Related to https://github.com/charmbracelet/lipgloss/issues/493. A test case was added to https://github.com/charmbracelet/glamour/pull/404.

fix(table): fix ellipsis (…) not always showing correctly

---

.editorconfig
.gitattributes
.vscode/settings.json

This adds an .editorconfig file to the repository to help maintain consistent formatting across the codebase. Particularly, it sets the final newline behavior for golden files. This is based on https://github.com/charmbracelet/lipgloss/pull/479

chore: add .editorconfig
