set.go

Fix a typo in the Inline doc comment

---

README.md

Thanks again to @kiyonlin and his superior logical abilities.

Remove irrelevant note about unset and falsey values

---

README.md

Added boolean to Inline() function

Fix example code to reflect api changes

---

set.go

Welp, it turns out that we already had this set in a much smarter place.

Revert "Keep margins, padding, widths, and heights positive"

---

runes.go
runes_test.go

This PR adds a utility function for styling individual runes in a string, which is useful for applying styles to specific parts of words.

Add StyleRunes function for styling specific runes in a string

---

borders.go

HiddenBorder() can be useful if you want to remove a border but maintain
layout positioning. This said, you can still apply a background color to
a hidden border.

Add HiddenBorder(), which renders a border comprised of spaces

---

color.go

Fix typo in AdaptiveColor's godoc comment

---

style.go

Simple method for checking the value of the style set with `SetString`. This would be useful when creating conditionals for passed style objects.

Add Value method

---

color.go

An acute catch by the ever-talented @muesli.

Protect against concurrent color profile access with a `sync.RWMutex`

---

style_test.go

Adds a simple benchmark for rendering a Lipgloss Style.

ci: add benchmark test for Style.Render

---

color_test.go

test: fix argument order

---

color.go

docs: fix RGBA godocs

---

go.mod
go.sum
style_test.go

Add tests for `lipgloss.Style`.

test: add Style tests

---

color_test.go
join_test.go
runes_test.go

Improve output and run as named tests.

test: simplify & improve output

---

README.md

docs: update readme footer

---

.github/workflows/coverage.yml

Reports coverage to coveralls.

ci: add coverage workflow

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml

ci: bump linter workflow

---

go.mod

we should probably retract v0.7.0!

fix: retract v0.7.0

---

style_test.go

chore: use io instead of deprecated ioutil pkg

---

color.go
get.go
join_test.go
position.go
renderer.go
set.go
unset.go
whitespace.go

docs: fix typos and clean up comments

---

README.md

docs: add FAQ

---

examples/go.mod
examples/go.sum

fix: go mod tidy examples

---

examples/table/chess/main.go
examples/table/languages/main.go
examples/table/mindy/main.go
examples/table/pokemon/main.go
table/model.go
table/rows.go
table/table.go
table/table_test.go

- wip: provide model interface for table data
- refactor: rename Model to Data
- refactor: add `Row` method
- refactor: use `Row` method
- fix: examples to Data interface

Table Data Interface

---

get.go

Fix GetBorderRightSize

---

borders.go

Adds new `Middle` borders in preparation for https://github.com/charmbracelet/lipgloss/pull/218
* `MiddleLeft`
* `MiddleRight`
* `Middle`
* `MiddleTop`
* `MiddleBottom`

Additional borders (Middle)

---

align.go
borders.go

Apply gofumpt to all files to correct minor formatting issues.

Apply gofumpt to all files

---

examples/go.mod
examples/list/glow/main.go
examples/list/sublist/main.go

Update Sublist Example

---

.github/workflows/release.yml
.goreleaser.yml

This will publish and announce releases on tag push.

feat(ci): use goreleaser for releases

---

join_test.go

This PR adds unit tests for `JoinHorizontal` function.

feat(test): add test for `JoinHorizontal`

---

examples/table/languages/main.go
examples/table/mindy/main.go
examples/table/pokemon/main.go

fixes https://github.com/charmbracelet/lipgloss/issues/385
With these changes:
Mindy:
Languages:
Pokemon:

fix(examples): fix out of range error

---

README.md

docs(readme): update example screenshot with blend

---

table/util.go

Fix comment on min func in utils

---

table/resizing.go
table/table_test.go
table/testdata/TestTableNoStyleFunc.golden

fix(table): fix panic when style func is `nil`

---

table/table.go
table/table_test.go
table/testdata/TestTableMarginAndRightAlignment.golden

- Fixes https://github.com/charmbracelet/glamour/issues/416
- Follow-up PR: https://github.com/charmbracelet/glamour/pull/417
Bug originally found on Glamour, but the relevant code lives here.

fix(table): fix wrong behavior of headers regarding margins

---

go.mod
go.sum

https://github.com/charmbracelet/lipgloss/pull/538#issuecomment-2955384621

chore(deps): update `github.com/charmbracelet/x/exp/golden`
